webapp: 
  build: ./webapp
  hostname: webapp
  command: /usr/sbin/httpd -DFOREGROUND
  ports: 
    - "80:80"
  volumes: 
    - ./laravel:/webapp
  links: 
    - mysql
    - memcached

mysql: 
 image: mysql:5.6
 environment: 
    - MYSQL_ROOT_PASSWORD=password
 ports: 
    - "3306:3306"
 volumes: 
    - /mnt/sda1/var/lib/mysql:/var/lib/mysql

memcached:
 image: memcached

